### ISSUE TITLE
error 500, querying manifest

### ISSUE THREAD

**Issue by zuba2033** [corincerami/mars-photo-api#173]
Hello, dear friend. 
I had a fully worked application, querying mnifest and photos  
From yesterday manifest query responds error 500 
Something wrong on server, or something changed in the way i shoud make queries?

**Comment by corincerami** [comment]
It looks like on November 28 when Heroku eliminated the free tier for Redis data, the manifest endpoint went down, as it was using Redis for caching manifests. I've upgraded to a paid Redis tier so this should be working again.

**Comment by zuba2033** [comment]
Thank you for your work!
